// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mint.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mint.Database.Migrations
{
    [DbContext(typeof(MintDbContext))]
    [Migration("20260627172511_RenameTables")]
    partial class RenameTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mint.Database.Entities.Ledger.Accounts.AccountEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastTransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_transaction_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("Mint.Database.Entities.Ledger.Transactions.TransactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("Mint.Database.Entities.System.AiPromptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxDuelsPerRun")
                        .HasColumnType("integer")
                        .HasColumnName("max_duels_per_run");

                    b.Property<string>("SystemPromptTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt_template");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserPromptTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_prompt_template");

                    b.HasKey("Id");

                    b.ToTable("ai_prompts");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.Duels.DuelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DuelType")
                        .HasColumnType("integer")
                        .HasColumnName("duel_type");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("duels");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.Duels.DuelOptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DuelId")
                        .HasColumnType("bigint")
                        .HasColumnName("duel_id");

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("option_code");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("option_text");

                    b.HasKey("Id");

                    b.HasIndex("DuelId");

                    b.ToTable("duel_options");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.UserCategories.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AiPromptId")
                        .HasColumnType("integer")
                        .HasColumnName("ai_prompt_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActiveForAI")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active_for_ai");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SearchKeywords")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("search_keywords");

                    b.HasKey("Id");

                    b.HasIndex("AiPromptId");

                    b.ToTable("user_categories");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.Votes.VoteEntity", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("DuelId")
                        .HasColumnType("bigint")
                        .HasColumnName("duel_id");

                    b.Property<decimal>("BetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("bet_amount");

                    b.Property<long>("ChosenOptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chosen_option_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("AccountId", "DuelId");

                    b.HasIndex("ChosenOptionId");

                    b.HasIndex("DuelId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_votes_duel_id_account_id");

                    b.ToTable("votes");
                });

            modelBuilder.Entity("Mint.Database.Entities.Users.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ExternalUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_user_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("LastAuthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_auth_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_name");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<byte>("SystemType")
                        .HasColumnType("smallint")
                        .HasColumnName("system_type");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "SystemType")
                        .IsUnique()
                        .HasDatabaseName("IX_users_external_user_id_system_type");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Mint.Database.Entities.Ledger.Accounts.AccountEntity", b =>
                {
                    b.HasOne("Mint.Database.Entities.Users.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mint.Database.Entities.Ledger.Transactions.TransactionEntity", b =>
                {
                    b.HasOne("Mint.Database.Entities.Ledger.Accounts.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.Duels.DuelEntity", b =>
                {
                    b.HasOne("Mint.Database.Entities.UserInteractive.UserCategories.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.Duels.DuelOptionEntity", b =>
                {
                    b.HasOne("Mint.Database.Entities.UserInteractive.Duels.DuelEntity", "Duel")
                        .WithMany("Options")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duel");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.UserCategories.CategoryEntity", b =>
                {
                    b.HasOne("Mint.Database.Entities.System.AiPromptEntity", "AiPrompt")
                        .WithMany("Categories")
                        .HasForeignKey("AiPromptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AiPrompt");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.Votes.VoteEntity", b =>
                {
                    b.HasOne("Mint.Database.Entities.Ledger.Accounts.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mint.Database.Entities.UserInteractive.Duels.DuelOptionEntity", "ChosenOption")
                        .WithMany("Votes")
                        .HasForeignKey("ChosenOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mint.Database.Entities.UserInteractive.Duels.DuelEntity", "Duel")
                        .WithMany("Votes")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ChosenOption");

                    b.Navigation("Duel");
                });

            modelBuilder.Entity("Mint.Database.Entities.System.AiPromptEntity", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.Duels.DuelEntity", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Mint.Database.Entities.UserInteractive.Duels.DuelOptionEntity", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
